baseURL = "https://fleetingbytes.github.io/family-recipes/"
title = "My Family Recipes"
timeZone = "Europe/Berlin"

# Book configuration
enableGitInfo = true
defaultContentLanguage = "en"

[markup]
    [markup.goldmark.renderer]
        # Needed for mermaid/katex shortcodes
        unsafe = true
    [makrup.tableOfContents]
        startLevel = 1

[module]
    [[module.imports]]
        path = "github.com/alex-shpak/hugo-book"

[languages]
    [languages.en]
        languageName = "English"
        languageCode = "en-GB"
        title = "Family recipes"
        weight = 1
    [languages.de]
        languageName = "Deutsch"
        languageCode = "de-DE"
        title = "Rezepte meiner Familie"
        weight = 2
    [languages.fr]
        languageName = "Français"
        languageCode = "fr-FR"
        title = "Les recettes de ma famille"
        weight = 3
    [languages.cs]
        languageName = "Česky"
        languageCode = "cs-CZ"
        title = "Rodinné recepty"
        weight = 4

[menus]
    [[menus.after]]
        name = "GitHub"
        url = "https://github.com/fleetingbytes/family-recipes"
        weight = 10
    [[menus.after]]
        name = "Hugo Book Theme"
        url = "https://themes.gohugo.io/hugo-book/"
        weight = 20

[params]
    BookTheme = "auto"
    BookToC = true
    BookSection = "docs"
    BookRepo = "https://github.com/fleetingbytes/family-recipes"
    BookCommitPath = "commit"
    BookEditPath = "edit/master/family-recipes"
    BookDateFormat = "January 2, 2006"
    BookSearch = true
    BookComments = false

[caches]
    [caches.images]
        dir = ":cacheDir/images"
